### ISSUE TITLE
Tests für 2024-01-09

### ISSUE THREAD

**Issue by nchiapol** [cevi/hitobito_cevi#195]
### Feature
 * :grey_question: Für Hitobito verwenden wir zukünftig eine semantische Versionierung startend bei 2.0.0. für den Release am 09. Januar 2024. 
_kann noch nicht getestet werden_
 * :grey_question: In Zukunft haben Hitobito Umgebungen mit gleichem Codestand auch die gleiche Versionsnummer. (#2214)  
_kann noch nicht getestet werden_
 * [x] Rollen, welche im Verlauf einer Person aufgeführt werden, werden gruppiert in «Aktive Rollen», «Zukünftige Rollen» und «Inaktive Rollen». (https://github.com/hitobito/hitobito/issues/2265)
 * [x] Es ist möglich, eine Rolle mit einem Von-Datum in der Zukunft zu erstellen. (#2237)
 * [x] Abonnements können nach Alter und Sprache gefiltert werden (#1919)
 * :grey_question: Rollen können ein Attribut haben, damit Personen ihre eigene Rolle entfernen dürfen. Standardmässig ist dieses Attribut auf allen Rollen inaktiv. (sac#133)  
_kann ohne entsprechende Rolle nicht getestet werden_
 * :grey_question: Das Bemerkungsfeld bei Anlässen wird nach einer gewissen Zeit automatisch gelöscht, um den Datenschutz garantieren zu können. Standardmässig ist dies bei allen Umgebungen auf 99 Jahre gesetzt. (#2129)  
_aktuell deaktiviert/ohne Effekt_
 * :grey_question: Pro Wagon können Kriterien definiert werden, damit gewisse Personen automatisch gelöscht werden. Beispielsweise, wenn jemand länger keine Rolle hatte, sich länger nicht eingeloggt hat, oder länger an keinem Anlass teilgenommen hat. Dieses Feature ist stanardmässig in allen Wagons deaktiviert. (#2106)  
_aktuell deaktiviert/ohne Effekt_
 * :grey_question: Personen können minimiert werden. Dabei werden sämtliche nicht zwingend notwendigen Daten der Person gelöscht. Unter welchen Bedingungen eine Person minimiert werden darf und welche Felder dabei gelöscht werden, kann pro Wagon definiert werden. Dieses Feature ist standartmässig in allen Wagons deaktiviert. (#2106)  
_aktuell deaktiviert/ohne Effekt_
 * :grey_question: Pro Wagon kann spezifiziert werden, dass bei einer Person nach einer gewissen Zeit ohne Login der Benutzer-Zugang entfernt wird. Dies ist standardmässig in allen Wagons deaktiviert (#2069)  
_aktuell deaktiviert/ohne Effekt_
 * :grey_question: Gruppen können mit statischen Bezeichnungen definiert werden. Die Namen dieser Gruppen können in Hitobito übersetzt werden, damit die Gruppennamen jeweils in der Sprache des Benutzers angezeigt werden. (#2219)  
_aktuell bei uns nicht verwendet_
 * [x] Die JSON:API für Gruppen wurde um diverse Attribute erweitert (#2243)

### Changes
 * [x] Mit dem Bootstrap 5 Upgrade erhält Hitobito ein neues Aussehen. Davon sind sämtliche Ansichten betroffen. Die Funktionen ändern sich dabei nicht. (https://github.com/hitobito/hitobito/issues/1754)
 * [x] Rollen mit einem Bis-Datum in der Vergangenheit werden sofort nach dem Speichern terminiert, anstatt in einem viertelstündlichen delayed-job. (#2245)
 * [x] Die Gruppen «Ohne Rollen» können nur noch Personen sehen, welche volle Lese- und Schreibrechte auf der jeweiligen Hauptgruppe haben. (#2208)

### Bugfixes
 * Wenn ein Enddatum in der Zukunft für eine Rolle festgelegt wird, werden alle 'after_destroy'-Hooks erst ab dem Zeitpunkt ausgeführt, an dem die Rolle tatsächlich als gelöscht gilt, anstatt sofort (#1748)  
_kann nicht sinnvoll getestet werden_
 * [x] Wird in der Suche nach Namen gesucht, welche Sonderzeichen beinhalten (z.B."«/» oder «&»), werden die Suchvorschläge nun korrekt angezeigt. (#2060)
 * Ist bei einer Person die Zweifaktorauthentifizierung aktiviert, funktioniert die «Remember Me» Funktion nun auch, wenn man sich von mehreren verschiedenen Geräten einloggt. (#2068)  
_nicht getestet_
 * Das Error-Handling bei zukünftig terminierten Rollen wurde verbessert. (#2255)  
_kann nicht sinnvoll getestet werden_

**Comment by nchiapol** [comment]
* erstellen von Rollen in der Zukunft funktioniert  
(getestet mit Frost und einer Helfer Rolle ab 1.8.2025, dann Start der Rolle angepasst auf 1.1.2024; Kontrolle verarbeitung noch ausstehend). 
* Gruppierung der Rollen nach  «Aktive Rollen», «Zukünftige Rollen» und «Inaktive Rollen» funktioniert  
Zukünftige Rollen werden auch auf dem Info-Tab (und nicht nur im Verlauf) angezeigt.

**Comment by nchiapol** [comment]
* Globale Filter bei Abos funktionieren  
   * Filter nach Sprache ist nutzlos bei uns (Es steht nur "Deutsch" zur Verfügung; Es nicht das Feld "Korrespondenzsprache" verwendet, sondern wahrscheinlich ein internes, nicht sichtbares Feld das bei allen unseren Einträgen auf Deutsch steht.)
   * Es kann nicht nur nach Alter sondern auch nach diversen anderen Feldern gefiltert werden (z.B. nach dem Cevinamen oder der Hauptmail-Adresse...)

**Comment by nchiapol** [comment]
* JSON-API funktioniert grundsätzlich
  * die API wird soweit ich das sehen kann bisher bei uns nicht verwendet
  * das verlinkte Ticket erwähnt, dass bei Gruppen z.B. parent_id enthalten sein sollte, das ist bei uns nicht der Fall (bzw. enthält `meta: {included: false}` evtl. müsste das irgendwo aktiviert werden...

**Comment by nchiapol** [comment]
* anliegen zum Bootstrap-Upgrade: https://github.com/hitobito/hitobito/issues/2317
* Bis-Datum in der Vergangenheit funktioniert nicht korrekt: https://github.com/hitobito/hitobito/issues/2333

**Comment by nchiapol** [comment]
* Kontrolle Rollen-Anpassung bei Frost: hat korrekt funktioniert.
* JSON-API: Erklärung in Ticket erhalten. Allg. ist die neue API noch sehr unvollständig
* Bootstrap-Bugs: diverse Fixes wurden umgesetzt, weiteres ist noch offen
* Bis-Datum wurde korrigiert.

Ich schliesse das Ticket, aus meiner Sicht gibt es keinen Blocker für das Release.
