### ISSUE TITLE
Tests: Release 2024-04

### ISSUE THREAD

**Issue by nchiapol** [cevi/hitobito_cevi#208]
Bitte dokumentiert hier, was ihr getestet habt und allfällige Probleme.

Features
- [x]  Der Dublettenabgleich wird neu auch direkt nach dem Erstellen einer Person sowie nach einer neuen Selbstregistration ausgeführt. (https://github.com/hitobito/hitobito/issues/2350/ und https://github.com/hitobito/hitobito/issues/2426)
  * Luchs: Duplikatprüfung funktionierte bei externer Anmeldung für einen Kurs oder beim Erstellen einer neuen Person in einer Ortsgruppe. Auch bei einer Selbstregistrierung auf einer Gruppe wo "Externe Registrierung" aktiviert ist wurde das Duplikat auf der Hauptadresse erkannt.
- [x]  Bei externen Registrierungen kann neu ausgewählt werden, ob eine zusätzliche Checkbox zur Abfrage der Volljährigkeit angezeigt werden soll. (https://github.com/hitobito/hitobito/issues/2404)
  * Luchs: Die Checkbox wird angezeigt wenn aktiviert und nicht angezeigt wenn nicht aktiviert. In beiden Fällen kann eine Registrierung vorgenommen werden.
- [x]  Das automatisch generierte Bemerkungsfeld in Anlässen kann neu in der Spaltenauswahl angezeigt und exportiert werden. (https://github.com/hitobito/hitobito/issues/2421)
    * Luchs: Das funktioniert sowohl für Kurse wie auch für Anlässe mit dem Export der ausgewählten Spalten und auch mit alle Angaben. Was auffällt ist das unser Feld nicht nur "Bemerkungen", sondern "Bemerkungen (Allgemeines, Gesundheitsinformationen, Allergien, usw.)" heisst. Dadurch wird die Spalte ziemlich breit. 
   - [x] Ich habe noch geprüft was passiert wenn man Zeilenumbrüche verwendet bei der Eingabe. Diese werden in der Tabelle mit "" ersetzt. D. h. der Text kann dann etwas zusammenhängen. Bspw. Allergie: Tomaten\r\nKrankenkasse: Visana" wird zu "Allergie TomatenKrankenkasse: Visana". Wäre das etwas das wir noch anmerken könnten? (anstatt mit "" zu ersetzen besser mit " ")
   * Carbon: Die Spalte kann zwar von allen eingeblendet werden, sie bleibt aber für die meisten Rollen leer, da normale Leiter keine Lese-Rechte an der Bemerkung haben. (Habe das entsprechend im original Issue kommentiert.)
- [x]  Qualifikationen werden neu im Verlauf einer Person aufgeführt. (https://github.com/hitobito/hitobito_sac_cas/issues/317)
    * Carbon: Qualifikationen sind im Verlauf vorhanden (ganz unten)
- [ ]  Rechnungen können neu auch die Stati "Teilbezahlt" oder "Überbezahlt" haben. (https://github.com/hitobito/hitobito_sww/issues/38)
- [ ]  Zahlungen, welche bei einem Import nicht zugewiesen werden können, werden neu persistiert und können exportiert werden (https://github.com/hitobito/hitobito/issues/1494)
- [x]  Auf Abos gibt es neu die Option, dass nur definierte Personen sich selbst für ein Abo an- oder abmelden können. Auch gibt es die Option zu definieren, ob man sich nur an- oder nur abmelden kann. (https://github.com/hitobito/hitobito/issues/2334)
    * Carbon: Scheint zu funktionieren. Cooles Feature. 
- [x]  Qualifikationsarten haben neu eine Einstellung für erforderliche Ausbildungstage, welche für eine erfolgreiche Verlängerung erreicht werden müssen. (https://github.com/hitobito/hitobito_sac_cas/issues/256)
   * Carbon: Einstellung ist Vorhanden, Auswirkung nicht getestet.
- [x]  Neu kann pro Umgebung definiert werden, ob Personen nach x Monaten ohne Login ihren Benutzerzugang verlieren sollen. Dieses Feature ist standardmässig für alle Kunden deaktiviert. (https://github.com/hitobito/hitobito/issues/2069)
    * Carbon: kann auf Integration nicht getestet werden
- [x]  Die OpenAPI Dokumentation zur neuen JSON:API wurde um technische Beschreibungen (Schemas) der erhältlichen Daten ergänzt. Dies erlaubt es API-Clients automatisch zu generieren, statt sie von Hand ausprogrammieren zu müssen. (#2134 - falsche Referenz?; wahrscheinlich https://github.com/hitobito/hitobito/issues/2345)
    * Carbon: Swagger-Seite: https://cevi.puzzle.ch/api-docs/ existiert, habe sie aber noch nicht weiter ausprobiert.
    - [ ] Luchs: Ich habe die Seite ausprobiert jedoch konnte ich keine gültigen Requests machen. Die angegebene Url war: https://cevi.puzzle.ch/api/://api/events?include=dates&token=xyz -> siehe /api/://api. Vermutlich ist das noch was falsch in der Konfiguration. In der Auswahlliste der Server wird auch nur :// - production angezeigt. Das sieht auch etwas komisch aus für eine Integrationsumgebung.

Changes
- [X]  Die JSON API wurde um zusätzliche Event Attribute erweitert. (https://github.com/hitobito/hitobito_sac_cas/issues/229)
   - [ ] Luchs: Die Anlässe und Kurse scheinen auf dem neuen Endpunkt alle vorhanden zu sein. Neue Felder sind: type, number, training_days, application_contact_id, applicant_count (ev. teamer count?), createdAt, updatedAt. Was nicht gut ist sind das folgende Felder die vorher da waren nicht mehr da sind: description, application_conditions, teamer_count, external_application_link. Bis auf teamer_count wären alle davon wichtig.
- [ ]  Das Dropdown "Rechnung erstellen" in Abos wurde vom Tab "Einstellungen" auf "Abonnenten" verschoben. (https://github.com/hitobito/hitobito/issues/2329)
- [x]  Die Einstellungen in Abos sind neu in mehrere Tabs gegliedert. (https://github.com/hitobito/hitobito/issues/2329)
  * Carbon: ok
- [x]  Verfügbare Abos in der Personenübersicht werden neu nach Layer sortiert. (https://github.com/hitobito/hitobito/issues/2337) 
   * Carbon: ok

Bugfixes
- [x]  Die Event Beschreibung wird bei externen Anmeldungen wieder korrekt formatiert. (https://github.com/hitobito/hitobito/issues/2252)
- [x]  Behebung von OAuth Serverfehlern (https://github.com/hitobito/hitobito/issues/2389)
    * Carbon: Beschriebener Fehler kann nicht mehr reproduziert werden
- [x]  Falls auf einem Abo keine Leserechte bestehen, erscheint der Name des Abos nicht mehr als Link. (https://github.com/hitobito/hitobito/issues/2331)
    - Carbon: Nur unvollständig umgesetzt
- [ ]  Die Navigation der Sammelrechnungen hat fälschlicherweise die Gruppenstruktur angezeigt. (https://github.com/hitobito/hitobito/issues/2487)
- [x]  Ist bei Kursen die Freigabe aktiviert, werden E-Mails an den Gruppenleiter wieder korrekt versendet. (https://github.com/hitobito/hitobito/issues/2120)
   - Carbon: Funktioniert wieder 
- [ ]  Behebung diverser Visual Bugs infolge des Bootstrap Upgrades.

Youth - muss noch etwas genauer angeschaut werden was das genau ist
- [ ] Registrierungsbutton (https://github.com/hitobito/hitobito_youth/pull/46)
- [ ] Household and Managed Adjustments (https://github.com/hitobito/hitobito_youth/pull/42)
- [ ] E-Mail Versand Prüfung Verwalter (https://github.com/hitobito/hitobito_youth/pull/47)
- [ ] Turbolink (https://github.com/hitobito/hitobito_youth/pull/49)
- [x] Verschiebung People Management (https://github.com/hitobito/hitobito_youth/pull/44)
     * Carbon: wurde verschoben, neuer Ort ist sinnvoll, Dokumentation ist deshalb nun aber veraltet (#209)
        - neuer Bug: https://github.com/hitobito/hitobito/issues/2523
        - behobener Bug: https://github.com/hitobito/hitobito/issues/2335
- [ ] Person entfernen (https://github.com/hitobito/hitobito_youth/pull/50)
- [ ] Address list entries (https://github.com/hitobito/hitobito_youth/pull/53)
- [x] https://github.com/hitobito/hitobito_youth/pull/57

Cevi
- [x] Alle Gremien Rollen können Anlässe erstellen (https://github.com/hitobito/hitobito_cevi/pull/125)
  * Luchs: Reguläre Gremienmitglieder können neu Anlässe erstellen

**Comment by patrickuhlmann** [comment]
Ich wollte noch die Rechnungen testen aber habe noch nie etwas damit gemacht und konnte weder die Rechnungseinstellungen sehen noch irgendwie eine Rechnung erstellen. Ev. kann mir das jemand von euch mal noch etwas zeigen.

**Comment by maede97** [comment]
@patrickuhlmann Du brauchst vermutlich noch die Rolle "Finanzverantwortlicher" auf der Ebene, auf der du die Rechnungen testen willst.

**Comment by nchiapol** [comment]
Nach dem Release ist bei Mönchi noch einen Bug aufgetaucht: Die Bestätigungen für die Anmeldung bei Anlässen (im Gegensatz zu Kursen) wurde immer wieder versendet. (d.h. Eltern haben wohl 10-12 mal das gleiche Mail erhalten...)

Der Bug war dann rasch gefixt.
