### ISSUE TITLE
Release 2024-07-02: Tests

### ISSUE THREAD

**Issue by nchiapol** [cevi/hitobito_cevi#221]
### Features
* [x] Sämtliche Adressen wurden anhand der neuen Norm ISO20022 strukturiert.  
:arrow_right: Ok. In Exporten (`.json`-API oder Excel/CSV/...) wird Strasse + Nummer in einem Feld zurückgegeben ([kommentar](https://github.com/cevi/hitobito_cevi/issues/221#issuecomment-2178506073))l Luchs: Aktualisieren funktioniert auch für Haushalt und zugewiesene Kinder. Bei Abos ist es ok für Adress- und Haushaltsliste. Bei Abos Abonnenten Export mit Spaltenauswahl ist das Feld Adresse aber leer https://github.com/hitobito/hitobito/issues/2704. Die Teilnehmerlisten bei Kursen sehen auch alle ok aus. Ist nur komisch das es manchmal ein und manchmal zwei Felder sind. Auch bei Anlässe sehen die Exporte gut aus. Bei Rechnungen sehen die ausgedruckten Rechnungen auch gut aus. Bei den Etiketten fehlt aber die Adresse. https://github.com/hitobito/hitobito/issues/2717

* [x] Personen, die in Haushalten oder durch den Elternzugang verwaltet werden, werden neu direkt auf der Personenübersicht dargestellt und können auch dort bearbeitet werden (Mit dem nächsten Release im Oktober werden diese Informationen anschliessend noch von der Info-Seite der Person entfernt, damit dies nur noch an einem Ort ist) (hitobito/hitobito#2622)
:arrow_right: Luchs: Die Verwaltung funktioniert. Konnte Kinder zuweisen/entfernen und auch Personen in den Haushalt aufnehmen und entfernen.

* [x] Bei Kursen kann neu definiert werden, ob neue Anmeldungen automatisch als Teilnehmende zugeteilt werden sollen, oder nicht. (hitobito/hitobito_sac_cas#358)  
:arrow_right: Habe das eben auch noch getestet, der Rückbau bei Kursen scheint korrekt geklappt zu haben
  - automatische und manuelle Zuteilung funktioniert korrekt, inkl. Warteliste
  - nationale Warteliste funktioniert
  - Feld "Minimale Teilnehmerzahl" ist vorhanden und wird anzeigt

  :warning: Bug: bei Anlässen wird die Option ebenfalls angezeigt, hat aber keine Wirkung (https://github.com/hitobito/hitobito/issues/2706)  

* [x] Für Qualifikationen können neu notwendige Ausbildungstage definiert werden. Die Qualifikation wird dann automatisch verlängert, sobald die notwendigen Ausbildungstage erreicht wurden (hitobito/hitobito_sac_cas#257)  
:arrow_right: Feld ist vorhanden; Funktionsweise habe ich nicht getestet, da für uns wohl nicht relevant.

* [x] Im Personenfilter kann neu nach Qualifikationen gefiltert werden. (hitobito/hitobito_sac_cas#333 / hitobito/hitobito_sac_cas#334 / hitobito/hitobito_sac_cas#500 / hitobito/hitobito_sac_cas#499)  
:arrow_right: War schon bisher möglich, neu scheinen weitere Auswahlmöglichkeiten dazugekommen zu sein. (vgl [kommentar](https://github.com/cevi/hitobito_cevi/issues/221#issuecomment-2185322026))

* [x] Im Personenfilter kann neu nach Personen ohne spezifische Rollen gefiltert werden. (hitobito/hitobito_sac_cas#335)  
:arrow_right: Habe nicht herausgefunden, wo etwas geändert hätte. (Vermutlich hatten wir das bereits in einem früheren Bug-Fix-Release erhalten). Luchs: Es ist das Kriterium "war die Rolle inaktiv" im "Personen filtern" wenn man in einer Gruppe auf das Tab Personen geht und dort das Fenster "Neuer Filter..." öffnet. Kam wohl effektiv mit dem Bugfix Release schon zu uns.

* [x] Kann ein Email aufgrund seiner Grösse nicht versendet werden, bekommt der/die Benutzer:in neu eine Rückmeldung, dass der Versand fehlgeschlagen ist. (hitobito/hitobito#2157)
:arrow_right: Luchs: habe ein Mail mit einem 25 MB Anhang gesendet und eine Nachricht vom Mailserver "552 5.3.4 Message size exceeds fixed limit" zurückerhalten

* [x] Es kann nun definiert werden, dass Kursfragen nach einer vorgegebenen Zeit automatisch gelöscht werden. Standardmässig ist hier kein Zeitraum definiert und Kursfragen werden auf unbestimmte Zeit gespeichert. (hitobito/hitobito_sac_cas#367)
:arrow_right: kann nicht getestet werden

* [x] Bei Anhängen auf Events kann neu definiert werden, für wen diese sichtbar sein sollen. (hitobito/hitobito_sac_cas#486)
:arrow_right: funktioniert

* [x] In der globalen Suche kann neu auch nach dem Geburtsdatum Personen gesucht werden (hitobito/hitobito_sac_cas#544)
:arrow_right: funktioniert

* [x] Die Basis für digitale Mitgliederausweise wurde in den Core verschoben. (hitobito/hitobito#2511)
:arrow_right: kann aktuell nicht getestet werden

### Changes
* [x] Die Gruppen-API wurde durch neue Attribute ergänzt. (hitobito/hitobito#2537)

* [x] Die JSON-API wurde um diverse Attribute erweitert. (hitobito/hitobito_sac_cas#430 / hitobito/hitobito_sac_cas#338)

* [x] Im Verlauf einer Person werden bei den Qualifikationen neu auch die noch offenen Ausbildungstage angezeigt. (hitobito/hitobito_sac_cas#332)
:arrow_right: für uns nicht relevant.

* [x] Bei der Personensuche erhält man neu ein Feedback, solange die Suche läuft. (hitobito/hitobito_sac_cas#478)
:arrow_right: getestet und funktioniert, rechts in der Suche erscheint ein rotierendes Icon

* [x] Statische Gruppen werden nun alphabetisch sortiert. (hitobito/hitobito#2673)
:arrow_right: bei uns gibt es keine statischen Gruppen

### Bugfixes
* [x] Der Personenimport aus CSV-Files funktioniert nun wieder korrekt. (hitobito/hitobito#2557)
:arrow_right: funktioniert

**Comment by maede97** [comment]
- Kurs: automatische Zuteilung TN hat geklappt.
- Gruppen-API hat neue Attribute.
- JSON-Api hat Kursarten (/api/event_kinds)
- Quali-Tage: scheint zu klappen. Konnte ich aber noch nicht ganz durchspielen.
- Personensuche: Siehe https://github.com/hitobito/hitobito_sac_cas/issues/478, Icon ist zwar da, aber kein Text wenn niemand gefunden. Dies wird erst angezeigt, wenn Enter gedrückt wird.

**Comment by maede97** [comment]
Anhänge sind nicht mehr für alle sichtbar:
https://cevi.puzzle.ch/groups/306/events/1225
![image](https://github.com/cevi/hitobito_cevi/assets/14098502/158465a4-a9de-4f45-b794-db196e9f3d19)

Ich habe drei Anhänge hochgeladen (jede Einstellung einmal). Was seht ihr davon?
- [x] Ich habe die Anhänge durch unterscheidbare ersetzt und getestet mit den Rollen: ohne, "Teilnehmer", Leiter"  
  die Sichtbarkeit entspricht den Tooltips

**Comment by maede97** [comment]
- [x] Adresse (ISO): Adresse ist neu aufgeteilt in Strasse und Hausnummer (separat). In der API ist dies aber noch nicht drin? (nur Feld "adress" auf einer Person)
  - Betrifft alle Exporte: https://github.com/hitobito/hitobito/issues/2705
  - kleiner Bug bei "Spaltenauswahl: https://github.com/hitobito/hitobito/issues/2704

**Comment by patrickuhlmann** [comment]
Fände es gut wenn wir einen kleinen Changelog versenden könnten (z. B. für die Sekis). Fokus auf relevante Punkte für uns und einfach verständlich. Hier ein Entwurf (gerne weiter bearbeiten):

**Changelog**

Personenverwaltung:
- Bei Adressen wird die Strasse und die Strassennummer getrennt (zwei Felder). Bestehende Adressen wurden migriert. In den Exporten werden die Informationen im Moment noch in eine Spalte kombiniert.
- Die Vorschau bei der Ausführung eines Personenimports (aus CSV) wird wieder angezeigt.

Kurse:
- Die Konfiguration für die automatische Zuteilung von neuen Anmeldungen ist nun von der Warteliste unabhängig
- Anmeldungen können auf eine nationale Warteliste gesetzt und von dort in andere Kurse vom gleichen Typ übernommen werden.

Abos
- Schlägt der Mailversand auf Grund der Mailgrösse (grosser Anhang) fehl, wird der Absender darüber informiert.

Events
- Es können Anhänge mit unterschiedlichen Sichtbarkeitsregeln hochgeladen werden: Leitungsteam, Leitungsteam und Teilnehmende oder Öffentlich. Die entsprechenden Personen sehen die Anhänge gemäss ihrer Rolle auf einem Anlass.

Suche
- Personen können mit dem Geburtsdatum gefunden werden (Format dd.mm.yyyy)


**Todo**

Ich glaube mit den obenstehenden Änderungen gibt es für uns noch zwei Entscheidungen zu treffen:
- [ ] Die Antworten auf Kursfragen können nach einer vorgegebenen Zeit automatisch gelöscht werden. Standartmässig ist das deaktiviert. Wollen wir das aktivieren?
- [ ] Wollen wir den digitalen Mitgliederausweis nutzen?

**Comment by patrickuhlmann** [comment]
Ich habe noch die Commits im hitobito_youth und hitobito_cevi überflogen. Glaube da gibt es nichts zusätzliches das wir anschauen müssen.

**Comment by nchiapol** [comment]
Neuerung bei Suche nach Qualifikation:

#### alt
![alt](https://github.com/cevi/hitobito_cevi/assets/1123483/ef3d70ad-2521-4ce4-a976-f0d2024b6955)


#### neu
![neu](https://github.com/cevi/hitobito_cevi/assets/1123483/866d1908-59b2-490a-b2a1-c08dccca92ab)

**Comment by nchiapol** [comment]
Danke euch beiden für die Tests und Rückmeldungen. 

@patrickuhlmann zum Changelog:
- ich habe bei den Kursen den Text angepasst, wir hatten bereits bisher die Möglichkeit für automatische Zuteilungen
- den Punkt zu den Qualifikationen habe ich gelöscht, mir wäre keine Qualifikation bekannt, bei der das greifen würde (alter Text unten)

Ausserdem zu deinen Fragen: 
- Automatische Löschung möchten wir definitiv. Haben wir einen Konsens für die Frist? 3 Monate nach letztem Kurstag?  
Grundsätzlich würde ich das aber wohl für den Herbst-Release aktivieren. So haben wir hinreichend Zeit die Frist zu diskutieren und das greift zusammen mit der AHV-Nummer ab 2025. Die Anpassung sollte problemlos via Pull-Request möglich sein.
- Beim digitalen Mitgliederausweis müssen wir sicher zuerst klären wie der genau Funktioniert und dann mit den relevanten politischen Verantwortlichen schauen ob da Interesse besteht.

```
Qualifikationen
- Automatische Verlängerung der Qualifikation bei Erreichen der notwendigen Ausbildungstage. Anzeige der offenen Ausbildungstage bis zur Reaktivierung
```

**Comment by nchiapol** [comment]
verbleibende Diskussionsthemen in eigene Issues verschoben
