### ISSUE TITLE
Release Tests 2024-10-01

### ISSUE THREAD

**Issue by nchiapol** [cevi/hitobito_cevi#227]
* [ ] ~JsonAPI: Neu können auch Rollen via API erstellt, mutiert und gelöscht werden. (hitobito/hitobito#2699)~
  * nicht getestet, bin aus Dokumentation nicht hinreichend schlau geworden.
* [ ] ~Mailchimp: Neu werden Adressen, welche über einen anderen Weg als von Hitobito in Mailchimp angelegt wurden, von Hitobito nicht mehr verändert oder gelöscht. (hitobito/hitobito#2752)~
  * schwierig zu testen
* [ ] ~Es wurde die Voraussetzung geschaffen, damit die noreply Adresse übersetzt werden kann. Zukünftig wird je nach ausgewählter Sprache der versendeten Email eine eigene noreply Adresse verwendet. Damit dies in einem spezifischen Wagon aktiv wird, ist noch eine Anpassung im Wagon notwendig. Bei Bedarf direkt bei Puzzle melden.(hitobito/hitobito_sac#600)~
  * schwierig zu testen
* [x] Seit Release 2.2.0 könnnen Haushalte über die Personenübersicht verwaltet werden (hitobito/hitobito#2622). Mit dem kommenden Release verschwindet die Option "Wohnt im Haushalt mit" nun von der Bearbeitungsseiten der Personendaten. (hitobito/hitobito#2624)
* [x] Bei Multiple Choice Fragen auf Events wird neu für jede Antwort eine neue Zeile verwendet. (hitobito/hitobito#2823)
* [ ] ~Haushalts Exporte mit grossen Datenmengen wurden verbessert und sollten zukünftig korrekt berechnet werden. (hitobito/hitobito#2212)]~
  * schwierig zu testen
* [ ] ~Mehrer Probleme mit den neu strukturierten Adressen wurden behoben. (hitobito/hitobito#2226)]~
  * unklar welche Probleme getestet werden müssten
  * unser wichtigstes Issue: https://github.com/hitobito/hitobito/issues/2705 ist noch nicht gefixt 

## Cevi/Youth
* [x] Änderungen bei den default Fragen (vgl hitobito/hitobito_youth#58)
  * [x] Bugs in Issue: doppelte Frage scheint korrigiert
  * [ ] Bugs in Issue: Mehrfachantworten sind weder sicht- noch konfigurierbar (Konfiguration ist aus meiner Sicht nicht zwingend solange die Frage deaktiviert und von Hand eine angepasste Frage angelegt werden kann.)
  * [x] AHV-Nr. ist auf dem Profil immer noch vorhanden.
* [x] 2FA für MIO und Dachverband
  * mit eigenem Usern getestet, 2FA wurde korrekt erzwungen und hat funktioniert
  * UX: https://github.com/hitobito/hitobito/issues/2872
* [x] Externe Gruppe in Gremien
  * ok auf Stufe Dachverband und MIO
* [x] Bugfix: Anmeldebestätigung Lager wird nicht an Verwalter*in versendet (hitobito/hitobito#2816)
* [x] Datenschutztext https://github.com/hitobito/hitobito_cevi/pull/142

## Bugs
Stand der Bugs gemäss https://github.com/cevi/hitobito_cevi/issues/131

**Comment by patrickuhlmann** [comment]
# Allgemeine Testfälle

## Cevi spezifisch

* [x] Bestandesmeldung https://github.com/hitobito/hitobito_cevi/issues/145
* [x] Spenderschutz

## Wichtige Funktionen

* Abos
  * [x] Neues Abo erstellen
  * [x] Für ein Abo anmelden
    * [ ]  Bugfix für: https://github.com/hitobito/hitobito/issues/2632
  * [x] Von einem Abo abmelden
* Rechnungen
  * [x] Neue Rechnung erstellen
  * [x] Rechnung stornieren
  * [x] Rechnung drucken
  * [x] Rechnung per Mail senden
* Ortsgruppen
  * [x] Neue Ortsgruppe inkl. Jungschar, Verein und Vorstand erstellen
  * [x] Neue Kinder erfassen https://github.com/hitobito/hitobito/issues/2873
  * [x] Neue Leiter erfassen
* Anlässe
  * [x] Neuen Anlass erstellen 
    * [ ] Bugfix für https://github.com/hitobito/hitobito/issues/2876
  * [x] Für einen Anlass anmelden
  * [x] Via Elternzugang für einen Anlass anmelden
  * [x] Von einem Anlass abmelden
  * [x] Für einen Anlass extern anmelden
* Kurse
  * [x] Neuen Kurs erstellen
  * [x] Für einen Kurs anmelden
  * [x] Für einen Kurs extern anmelden
  * [x] Via Elternzugang für einen Kurs anmelden
  * [x] Export Teilnehmerliste
* [x] Schnellsuche
* Sicherheit
  * [x] Login senden
  * [x] Passwort überschreiben
  * [x] Login sperren/Login entsperren
  * [x] Rollen die auf mich Zugriff haben auflisten
  * [x] 2FA einrichten für einen Benutzer wo das nicht notwendig wäre https://github.com/hitobito/hitobito/issues/2874
  * [x] 2FA einrichten beim ersten Login mit einem Benutzer wo das erzwungen wird
  * [x] Neuen API Key erstellen
* API
  * [x] [Swagger UI](https://cevi.puzzle.ch/api-docs/index.html)
  * [x] Person API -> Mitglieder einer Gruppe
    * [x] Personen Detail
  * [x] Event API -> Anlässe einer Gruppe https://github.com/hitobito/hitobito/issues/2890
  * [x] Course API -> Kurse einer Gruppe

**Comment by patrickuhlmann** [comment]
Habe hier im Cevi Wiki eine Seite zu 2FA angelegt: https://wiki.cevi.ch/index.php/Cevi.db_2FA

**Comment by patrickuhlmann** [comment]
Betreffend Rollen. Das sind vermutlich diese neuen Endpunkte:
![image](https://github.com/user-attachments/assets/de9c89d9-8a0a-4c6a-8015-2d11e28b883d)

**Comment by nchiapol** [comment]
@patrickuhlmann Genau, die Roles Endpunkte habe ich in Swagger auch gesehen, aber nicht herausgefunden welche Werte ich Create Role mitgeben muss um einer bestimmten Person eine gewünschte Rolle in einer Zielgruppe zu geben.

**Comment by patrickuhlmann** [comment]
**Release Notes**

Elternzugang
* Neu werden Anmeldebestätigungen bei Lageranmeldungen an die Eltern versendet. hitobito/hitobito#2816

Haushalte
* Die Option "Wohnt im Haushalt mit" verschwindet von den Bearbeitungsseiten der Personendaten. Die Verwaltung über die Personenübersicht funktioniert weiterhin. hitobito/hitobito#2624

API
* Rollen können via API erstellt, geändert oder entfernt werden. hitobito/hitobito#2699

Mailversand
* Adressen in Mailchimp, welche nicht aus Hitobito stammen werden nicht mehr verändert oder gelöscht. hitobito/hitobito#2752

Events
* Bei Multiple Choice Fragen auf Events wird neu für jede Antwort eine neue Zeile verwendet. (hitobito/hitobito#2823)

Export
* Haushalts Exporte mit grossen Datenmengen wurden führen nicht mehr zu Fehlern. (hitobito/hitobito#2212)]

Gremien
* Gremien erhalten die Möglichkeit externe Gruppen zu erstellen. Dies hat den Vorteil das Mitglieder dieser Gruppen durch die Erfassung keine Leserechte auf der Ebene Cevi Schweiz/Region erhalten. Dies kann bspw. genutzt werden um Listen von Interessenten oder Ehemaligen zu führen etc. https://github.com/hitobito/hitobito_cevi/issues/134

AHV-Nummer
* Die AHV-Nummer ist neu auf allen Anlässen als Standardfrage vorhanden. Für Events, welche vor dem Release erstellt wurden ist die Option "nicht angezeigt" ausgewählt. Bei neuen Events muss jeweils bei der Speicherung eine Option ausgewählt werden. Es handelt sich um Vorbereitungsarbeiten für den nächsten Schritt, wo die AHV-Nummer von der Person entfernt wird und nur noch auf den Anlässen existiert. Später wird diese dann nach einer bestimmten Frist automatisch gelöscht.

Sicherheit
* Für sensitive Rollen auf der Ebene Region oder Cevi Schweiz (Mitarbeiter, Gremienmitglieder, Vorstand) ist eine Zwei-Faktor Authentifizierung zwingend. Siehe dazu https://wiki.cevi.ch/index.php/Cevi.db_2FA. https://github.com/hitobito/hitobito_cevi/issues/133

Datenschutz
* Bei der Erfassung von Personen wir nicht mehr wie bis anhin die Zustimmung der erfassten Person bestätigt, sondern lediglich dass diese über die Datenschutzerklärung informiert wurde. Dies entspricht besser der Realität. https://github.com/hitobito/hitobito_cevi/pull/142

Bekannte Bugs und Fehler sind hier dokumentiert: https://wiki.cevi.ch/index.php/CeviDB_Bugs

**Comment by patrickuhlmann** [comment]
~Neues Release Date: 17.10.2024~

**Comment by nchiapol** [comment]
Neues Release Date: 29.10.2024  09.00 - 11.00

**Comment by tschuepbach** [comment]
Scheint soweit alles zu funktionierten.

Betreffend https://github.com/hitobito/hitobito_youth/issues/58 wird die Standardfrage "Ich habe Interesse an einer Mitarbeit im Leiterteam in einer der folgenden Rollen" fälschlicherweise auch bei Anlässen angezeigt.

**Comment by nchiapol** [comment]
Release ist erfolgt, für die Standardfrage gibt es ein neues, eigenes Issue
