### ISSUE TITLE
Release Tests 2025-01-14

### ISSUE THREAD

**Issue by nchiapol** [cevi/hitobito_cevi#234]
### Features
* [x] In den Rechnungseinstellungen können nun Textvorlagen für Rechnungen erstellt werden. (hitobito/hitobito_sww#28)
* [x] In den Rechnungseinstellungen kann nun definiert werden, ob der Rechnungstext auf der Mahnung erneut aufgedruckt werden soll oder nicht. ((hitobito/hitobito_sww#174)
  * Option exisitiert und scheint korrekt zu funtionieren.
* [x] Auf Events können nun mehrer Anhänge gleichzeitig hochgeladen werden. (hitobito/hitobito#3017)
* [x] Vom Personen-Tab einer Gruppe können neu mehrere Personen gleichzeitig zu einem Event eingeladen werden. Ausserdem kann die Liste der Einladungen für einen Event nun als CSV exportiert werden. (hitobito/hitobito/pull/2486)
  * [ ] Bug: Liste zeigt nur Zeit statt Datum ~https://github.com/hitobito/hitobito/issues/3104~ https://github.com/hitobito/hitobito/issues/3069

### Changes
* [x] Für die externe Registrierung können nun nur noch Rollen ohne Rechte ausgewählt werden. (hitobito/hitobito#2357)
  * funktioniert korrekt, führt dazu, dass man sich nicht mehr direkt in eine Stufe anmelden kann, da in einer Stufe keine Rolle ohne Rechte existiert.
* [ ] ~Es wurde verhindert, dass grosse Exports alle Ressourcen beanspruchen können und damit andere Hintergrundjobs blockieren. (hitobito/hitobito_sac_cas#1354)~
  * kann nicht sinnvoll getestet werden
* [x] Die Kurs API kann nun auch das Attribut «Leaders» ausgeben. (hitobito/hitobito_sac_cas#1265)
  * das Attribut kann bei allen events übergeben werden ohne einen Fehler auszulösen
  * die Leader-Daten werden aber nur bei Kursen korrekt ausgeliefert, bsp für eine Funktionierende URL: https://cevi.puzzle.ch/api/events/1178?include=leaders,dates
* [x] ~Geburtsdaten auf Französisch und Italienisch können bei der Selbstregistration nun auch mit einem Punkt als Trennung eingegeben werden. (hitobito/hitobito_sac_cas#1334)~
  * Wir haben nur eine Sprache

### Bugfixes
* [ ] Exporte von Etiketten werden neu korrekt analog der aktuell ausgewählten Sortierung in der Personenübersicht sortiert (Standartwert: Alphabetisch nach Nachnamen). (hitobito/hitobito#2199)
* [ ] Gross- und Kleinschreibung bei Emails wird nun wieder korrekt geprüft.
* [ ] Archivierte Gruppen können nun korrekt gelöscht werden. (hitobito/hitobito#2000)
  * Lösch-Option ist vorhanden, funktioniert aber nicht (500er)
* [ ] Personen in «ohne Rollen» Gruppen können wieder korrekt gelöscht werden. (hitobito/hitobito#1780)
* [ ] Manuell zu Abos hinzugefügte Personen werden vom Abo wieder korrekt berücksichtigt. (hitobito/hitobito#3058)
* [ ] Qualifikationen können in Personenfiltern wieder korrekt ausgewählt werden. (hitobito/hitobito#3025)
* [ ] Diverse Server Errors wurden gefixt, was zu weniger 500er Fehlern führen sollte.
* [ ] Die Performance bei der globalen Suche wurde verbessert.

**Comment by patrickuhlmann** [comment]
Du hast schon viel angekreuzt aber das Release ist noch gar nicht deployed oder sehe ich da was falsch?

**Comment by nchiapol** [comment]
> Du hast schon viel angekreuzt aber das Release ist noch gar nicht deployed oder sehe ich da was falsch?

Die Integration ist seit 2 Wochen im Release-Freeze. Entsprechend können/sollten wir dort wie bei früheren Releases testen. Oder was war deine Frage?

**Comment by patrickuhlmann** [comment]
> > Du hast schon viel angekreuzt aber das Release ist noch gar nicht deployed oder sehe ich da was falsch?
> 
> Die Integration ist seit 2 Wochen im Release-Freeze. Entsprechend können/sollten wir dort wie bei früheren Releases testen. Oder was war deine Frage?

Ja genau das war meine Frage. Irgendwie habe ich kein Releasemail erhalten wie wir das früher immer erhalten hatten. Ging bei deinem Mail davon aus das es ab 14.01 auf der Integration bereitsteht, nicht dass dies der Releasetermin ist.

**Comment by patrickuhlmann** [comment]
## Cevi spezifisch

* [X] Bestandesmeldung
* [X] Spenderschutz

## Wichtige Funktionen

* Abos
  * [X] Neues Abo erstellen
  * [X] Für ein Abo anmelden
  * [X] Von einem Abo abmelden
* Rechnungen
  * [X] Neue Rechnung erstellen
  * [X] Rechnung stornieren
  * [X] Rechnung drucken
  * [X] Rechnung per Mail senden
* Ortsgruppen
  * [X] Neue Ortsgruppe inkl. Jungschar, Verein und Vorstand erstellen
  * [X] Neue Kinder erfassen
  * [X] Eltern als Verwalter für ein Kind erfassen
  * [X] Neue Leiter erfassen
* Anlässe
  * [X] Neuen Anlass erstellen
  * [X] Für einen Anlass anmelden
  * [X] Via Elternzugang für einen Anlass anmelden
  * [X] Von einem Anlass abmelden
  * [X] Für einen Anlass extern anmelden
* Kurse
  * [x] Neuen Kurs erstellen
  * [x] Für einen Kurs anmelden
  * [x] Für einen Kurs extern anmelden
  * [x] Via Elternzugang für einen Kurs anmelden
  * [x] Export Teilnehmerliste
* [x] Schnellsuche
* Sicherheit
  * [x] Login senden -> Mail in Mailtrap.io erhalten
  * [x] Passwort überschreiben - Mail in Mailtrap.io erhalten
  * [x] Login sperren/Login entsperren -> Gibt keine Mails
  * [x] Rollen die auf mich Zugriff haben auflisten
  * [x] Neuen API Key erstellen
* API
  * [x] [Swagger UI](https://cevi.puzzle.ch/api-docs/index.html)
  * [x] /api/groups/{id} -> Eine Gruppe abrufen
  * [x] /api/people/{id} Personen Detail
  * [x] /api/event/{id} -> Einen Anlass abrufen

**Comment by patrickuhlmann** [comment]
Habe noch kurz beim youth und cevi Wagon geschaut. Es gab noch einen Change der die Sortierung nach Ortsgruppen in Events deaktiviert hat: https://github.com/hitobito/hitobito_cevi/pull/147/files der ist aber schon am 29.10 respektive mit dem "Nachrelease" im November auf Prod gerutscht. Ist das ok oder müssen wir noch was dazu sagen? Wäre eigentlich schon schön wenn man danach sortieren könnte. Wurde das einfach ohne Info deaktiviert?

**Comment by nchiapol** [comment]
Well spotted, wegen der Sortierung nach Ortsgruppen. Beim Personen-Tab der Gruppen gibt es die Ortsgruppe gar nicht mehr (dafür aber die "Hauptgruppe" die uns wohl nie interessiert hat.) 

> Ist das ok oder müssen wir noch was dazu sagen? 
Ich denke, das sollten wir zurückmelden. Kannst du dich darum kümmern?

Ich schreib mir das auch noch auf für die nächste Besprechung mit Puzzle.

**Comment by nchiapol** [comment]
Sortierung von Ortsgruppen wurde hier behandelt https://github.com/hitobito/hitobito_cevi/issues/151
